name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create environment.prod.ts
        run: |
          cat <<EOF > src/environments/environment.ts
          export const environment = {
            production: false,
            apiUrl: '${{ secrets.PROD_API_URL }}',
            googleMapsApiKey: '${{ secrets.GOOGLE_MAPS_API_KEY }}'
          };
          EOF
          cat <<EOF > src/environments/environment.prod.ts
          export const environment = {
            production: true,
            apiUrl: '${{ secrets.PROD_API_URL }}',
            googleMapsApiKey: '${{ secrets.GOOGLE_MAPS_API_KEY }}'
          };
          EOF
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NWPOSTGRE21 }}
          channelId: live
          projectId: northwind-fe-postgre